// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace ReactiveMachine.TelemetryBlobWriter
{
    public class Configuration
    {
        [JsonIgnore]  // do not write connection strings to storage
        public string ConnectionString;

        /// <summary>
        /// The name of the blob container in which to store the results
        /// </summary>
        public string BlobContainer = "reactive-machine-results";

        /// <summary>
        /// Whether to store events generated by the host
        /// </summary>
        public bool CollectHostEvents;

        /// <summary>
        /// Whether to store caller-events generated by the application
        /// </summary>
        public bool CollectApplicationEvents;

        /// <summary>
        /// Whether to store caller-events generated by the application
        /// </summary>
        public bool CollectThroughput;
    }
}
